const char *defaultUserConfig =
    "{\n"
    "  \"audio\": {\n"
    "    \"initalVolume\": 130,\n"
    "    \"minVolume\": 0,\n"
    "    \"maxVolume\": 255,\n"
    "    \"volumeEncoderStep\": 5\n"
    "  },\n"
    "  \"slots\": [\n"
    "    \"/PAW01\",\n"
    "    \"/PAW02\",\n"
    "    \"/PAW03\",\n"
    "    \"/PAW04\"\n"
    "  ],\n"
    "  \"wifi\": {\n"
    "    \"enabled\": false,\n"
    "    \"ssid\": \"myssid\",\n"
    "    \"password\": \"mypassword\"\n"
    "  },\n"
    "  \"hbi\": {\n"
    "    \"reverseNose\": false,\n"
    "    \"releaseInsteadOfPress\": false,\n"
    "    \"ioMapping\": [\n"
    "        16,\n"
    "        16,\n"
    "        16,\n"
    "        16,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        33,\n"
    "        32,\n"
    "        34,\n"
    "        35,\n"
    "        36\n"
    "    ]\n"
    "  }\n"
    "}\n";