const char *defaultUserConfig =
    "{\n"
    "  \"name\": \"Baer\",\n"
    "  \"timezone\": \"CET-1CEST,M3.5.0,M10.5.0/3\",\n"
    "  \"batteryPresent\": true,\n"
    "  \"audio\": {\n"
    "    \"initalVolume\": 130,\n"
    "    \"minVolume\": 0,\n"
    "    \"maxVolume\": 255,\n"
    "    \"volumeEncoderStep\": 5,\n"
    "    \"mono\": false\n"
    "  },\n"
    "  \"slots\": [\n"
    "    \"/PAW01\",\n"
    "    \"/PAW02\",\n"
    "    \"/PAW03\",\n"
    "    \"/PAW04\"\n"
    "  ],\n"
    "  \"wifi\": {\n"
    "    \"enabled\": false,\n"
    "    \"ssid\": \"myssid\",\n"
    "    \"password\": \"mypassword\"\n"
    "  },\n"
    "  \"hbi\": {\n"
    "    \"reverseNose\": false,\n"
    "    \"releaseInsteadOfPress\": false,\n"
    "    \"ledBrightness\": 255,\n"
    "    \"ioMapping\": [\n"
    "        1,\n"
    "        1,\n"
    "        1,\n"
    "        1,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        0,\n"
    "        4,\n"
    "        2,\n"
    "        3,\n"
    "        5,\n"
    "        6\n"
    "    ]\n"
    "  }\n"
    "}\n";